<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
    </style>
</head>
<body>
<h1>Link for confirmation:</h1>
<img src="https://imageio.forbes.com/specials-images/imageserve/6477e7e4d5a222cb969b8c15/Ministry-of-Tourism-of-Ecuador-Typical-Dishes/960x0.jpg?format=jpg&width=960" alt="">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>