<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Thank You for Registering!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            text-align: center;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: cadetblue;
        }

        p {
            color: #555;
            font-size: 18px;
            margin-bottom: 20px;
        }

        .image-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .image-container img {
            width: 200px;
            height: 200px;
            margin: 0 10px;
            border-radius: 10px;
            border: 5px solid #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Thanks for your register!</h1>
    <p>Your email was correctly verified!</p>
    <div class="image-container">
        <img src="https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg" alt="Flag of Ecuador">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKhS9XUlniiykPkqYz9IsadyXG6_qmWe3EvkEO3x9pBQ&s" alt="Ecuadorian Food">
        <img src="https://i0.wp.com/plazamercado.shop/wp-content/uploads/2020/09/Platano-verde.jpg?fit=800%2C800&ssl=1" alt="Platano Verde">
    </div>
</div>
</body>
</html>